function [wrapperPath, headerDir] = sanitiseLoadlibraryHeader(headerPath)
%SANITISELOADLIBRARYHEADER  Emit a minimal header for MATLAB loadlibrary.
%
%   [wrapperPath, headerDir] = cigre.util.sanitiseLoadlibraryHeader(headerPath)
%
%   Writes a small, self-contained C header in tempdir that declares only
%   what MATLAB needs to interoperate with a CIGRE DLL at run time:
%     - the basic CIGRE typedefs (char_T, int8_T, ..., real64_T),
%     - the IEEE_Cigre_DLLInterface_Instance struct, and
%     - the five Model_* function prototypes invoked via calllib.
%
%   The full IEEE/Cigre header (IEEE_Cigre_DLLInterface.h) is intentionally
%   NOT included.  Its `union DefaultValueU`/`MinMaxValueU` declarations and
%   nested `Parameter`/`Model_Info` typedefs trip up the loadlibrary header
%   parser on some MATLAB releases (notably R2023b): the parser bails
%   mid-file and silently drops every typedef and prototype that follows,
%   including IEEE_Cigre_DLLInterface_Instance.  loadlibrary then succeeds
%   without throwing, but `libpointer('s_IEEE_Cigre_DLLInterface_Instance',
%   ...)` later fails with "Type was not found".
%
%   By redeclaring the small subset we actually use ourselves, the parser
%   never sees the problem cases and the Instance struct always registers.
%
%   The original `headerPath` is accepted (and `headerDir` returned) only
%   for backwards compatibility with existing callers that still pass an
%   `'includepath', headerDir` pair to loadlibrary.

    headerPath = char(headerPath);
    headerDir  = fileparts(headerPath);

    wrapperPath = fullfile(tempdir, ...
        sprintf('cigre_loadlib_wrapper_%s.h', char(cigre.util.uuid())));

    fid = fopen(wrapperPath, 'w');
    if fid < 0
        error('CIGRE:sanitiseLoadlibraryHeader:WriteFailed', ...
            'Could not write loadlibrary wrapper header at %s', wrapperPath);
    end
    closeFid = onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, '/* Auto-generated by cigre.util.sanitiseLoadlibraryHeader */\n');
    fprintf(fid, 'typedef char            char_T;\n');
    fprintf(fid, 'typedef signed char     int8_T;\n');
    fprintf(fid, 'typedef unsigned char   uint8_T;\n');
    fprintf(fid, 'typedef signed short    int16_T;\n');
    fprintf(fid, 'typedef unsigned short  uint16_T;\n');
    fprintf(fid, 'typedef signed int      int32_T;\n');
    fprintf(fid, 'typedef unsigned int    uint32_T;\n');
    fprintf(fid, 'typedef float           real32_T;\n');
    fprintf(fid, 'typedef double          real64_T;\n');
    fprintf(fid, '\n');
    fprintf(fid, 'typedef struct _IEEE_Cigre_DLLInterface_Instance {\n');
    fprintf(fid, '    void *          ExternalInputs;\n');
    fprintf(fid, '    void *          ExternalOutputs;\n');
    fprintf(fid, '    void *          Parameters;\n');
    fprintf(fid, '    real64_T        Time;\n');
    fprintf(fid, '    const uint8_T   SimTool_EMT_RMS_Mode;\n');
    fprintf(fid, '    const char_T *  LastErrorMessage;\n');
    fprintf(fid, '    const char_T *  LastGeneralMessage;\n');
    fprintf(fid, '    int32_T *       IntStates;\n');
    fprintf(fid, '    real32_T *      FloatStates;\n');
    fprintf(fid, '    real64_T *      DoubleStates;\n');
    fprintf(fid, '} IEEE_Cigre_DLLInterface_Instance;\n');
    fprintf(fid, '\n');
    fprintf(fid, 'int32_T Model_FirstCall(IEEE_Cigre_DLLInterface_Instance* instance);\n');
    fprintf(fid, 'int32_T Model_CheckParameters(IEEE_Cigre_DLLInterface_Instance* instance);\n');
    fprintf(fid, 'int32_T Model_Initialize(IEEE_Cigre_DLLInterface_Instance* instance);\n');
    fprintf(fid, 'int32_T Model_Outputs(IEEE_Cigre_DLLInterface_Instance* instance);\n');
    fprintf(fid, 'int32_T Model_Terminate(IEEE_Cigre_DLLInterface_Instance* instance);\n');
end
